/*
 * Review validation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Adapters.Rest.Generated.Attributes;
using Adapters.Rest.Generated.Models;

namespace Adapters.Rest.Generated.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class ReviewsApiController : ControllerBase
    { 
        /// <summary>
        /// Gets a list of reviews.
        /// </summary>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/api/reviews")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(ReviewsResponse))]
        public abstract Task<IActionResult> GetReviews();

        /// <summary>
        /// Starts the review validation process.
        /// </summary>
        /// <param name="registerReview"></param>
        /// <response code="202">Accepted</response>
        [HttpPost]
        [Route("/api/reviews")]
        [Consumes("application/json")]
        [ValidateModelState]
        public abstract Task<IActionResult> ValidateReview([FromBody]RegisterReview registerReview);
    }
}
